server:
  port: 9001

spring:
  application:
    name: springcloud-demo
  freemarker:
    #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: true
    #指定HttpSession的属性是否可以覆盖controller的model的同名项
    allow-session-override: true
    #是否开启template caching.
    cache: true
    #设定Template的编码.
    charset: UTF-8
    #是否检查templates路径是否存在.
    check-template-location: true
    #设定Content-Type.
    content-type: text/html
    #是否允许mvc使用freemarker.
    enabled: true
    #设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-request-attributes: true
    #设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中.
    expose-session-attributes: true
    #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    #视图加载顺序
    order: 0
    #是否优先从文件系统加载template，以支持热加载，默认为true
    prefer-file-system-access: true
    #设定freemarker模板的前缀.
    #prefix:
    #指定RequestContext属性的名.
    request-context-attribute: request
    #设定FreeMarker keys.
    settings:
      #如果变量为null,转化为空字符串，比如做比较的时候按照空字符串做比较
      classic_compatible: true
      #去掉多余的空格，非常有用
      whitespace_stripping: true
      #模板更新时间，这里配置是1秒更新一次，正式环境设置为3600秒
      template_update_delay: 1
      #中国
      locale: zh_CN
      #编码utf8
      default_encoding: utf_8
      #url编码utf8
      url_escaping_charset: utf_8
      #显示日期格式
      date_format: yyyy-MM-dd
      #显示时间格式
      time_format: HH:mm:ss
      #显示日期时间格式
      datetime_format: yyyy-MM-dd HH:mm:ss
      #数字格式
      number_format: 0.######
      output_encoding: UTF-8
      #布尔型格式
      boolean_format: true,false
      #宏定义
      #auto_import="/common/index.ftl" as ui
      tag_syntax: auto_detect
    #设定模板的后缀.
    suffix: .ftl
    #设定模板的加载路径，多个以逗号分隔，默认: ["classpath:/templates/"]
    template-loader-path: classpath:/templates/
    #指定使用模板的视图列表. White list of view names that can be resolved.
    #view-names